apiVersion: v2
name: istiod
description: Istiod
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.11.1

dependencies:
  - name: base
    version: "1.15.1"
    repository: "https://nexus.bumble.dev/repository/helm-istio-chart/"
  - name: istiod
    version: "1.15.1"
    repository: "https://nexus.bumble.dev/repository/helm-istio-chart/"

sources:
  - https://github.com/istio/istio

